### ISSUE TITLE
Configuration: How should it work?

### ISSUE THREAD

**Issue by luiz-otavio** [rede-dark/CloverMod#3]
I need some properties to attach those values in configuration, can anyone help me?

**Comment by Eisenbahn** [comment]
Max Stats por Stat (ou tudo mesmo como no dbc)
Permitir Além do Limite ou não
Taxa de TP ganho, não sei se tá incluindo TP no mod
Attribute's TP cost mulipier. The higher amount the higher will be the increase after each upgrade. (default: 1.6)
taxa de regen de mana/estamina/hp
multiplicador de dano final e custo de estamina nos moves e custo de mana nas magias

**Comment by luiz-otavio** [comment]
The configuration has been solved.

**Comment by PeterStark000** [comment]
- Multiplicador de XP (todo os dias) - Boolean ?
- Multiplicador de XP (finais de semana) - Sexta, sábado, domingo - Boolean ?
